### ISSUE TITLE
CustomJS not loading on startup

### ISSUE THREAD

**Issue by rossoj85** [saml-dev/obsidian-custom-js#36]
This seems to only happen at startup. If I flip to a different note and then back again, everything loads. Is there any way to force the load before startup across all code fences? 

Thanks!

<img width="700" alt="image" src="https://user-images.githubusercontent.com/25422645/201587992-bf327d51-c218-4952-aad5-2c99c2bb3ebb.png">

**Comment by willasm** [comment]
This is what I use to load my dataview script on startup and it gets rid of the same error you are getting.
`startup.md`

```dataviewjs
// required by dataview for getWeather functions
let tpl = this.app.plugins.plugins['templater-obsidian'].templater;
```

I load it with templater 'Startup Templates' option.
Without defining tpl (a variable used in my script) on startup I was getting the same error even though it is already defined in my script? I had the same effect where changing from this note to another and back fixed it but with this startup script that is no longer necessary. Hopefully this will help you.

**Comment by saml-dev** [comment]
Check out the [Asynchronous Usage](https://github.com/saml-dev/obsidian-custom-js#asynchronous-usage) section of the README. It might fix the problem for both of you.

**Comment by charleshan** [comment]
I tried adding `await forceLoadCustomJS();` as described in the README but then Obsidian renders the page before Dataview finishes indexing, resulting `Dataview: No results to show for table query.`

Works fine without CustomJs if the code is added to the file directly.

**Comment by dxcore35** [comment]
@charleshan Hello! Thank you for your insights! May I know what exactly you have added into the JS file?
I tried to just add `await forceLoadCustomJS()` but the code add syntax error.

**Comment by yustinrd** [comment]
I have the same issue 
```dataviewjs
await forceLoadCustomJS();
const {getSome} = commonJS;
```

Evaluation Error: ReferenceError: commonJS is not defined
    at eval (eval at <anonymous> (plugin:dataview), <anonymous>:2:20)
    at async DataviewJSRenderer.render (plugin:dataview:18402:13)

**Comment by saml-dev** [comment]
@yustinrd you typed `commonJS` instead of `customJS`.
