### ISSUE TITLE
Newbie question on how to import luxon

### ISSUE THREAD

**Issue by tilmanbergt** [saml-dev/obsidian-custom-js#37]
Hi, I lile this library, I now try to import luxon to use those classes like DateTime. 

My class starts with 
class TaskChecker {
		import DateTime from "./luxon.js";
...
}
But this makes it unusable. Luxon file resides in the same folder as my TaskChecker. Without this line it works really nice. Could not find any guide in the internet on how to do this properly. Can someone please give me a hint? 

If you need more infomation please let me know. 

Here is the error shown, but this seems to be what comes up whenever the file is completely syntactically invalid: 
Evaluation Error: TypeError: Cannot read properties of undefined (reading 'showMonthly')
    at eval (eval at <anonymous> (plugin:dataview), <anonymous>:2:13)
    at DataviewInlineApi.eval (plugin:dataview:19673:16)
...

**Comment by saml-dev** [comment]
Unfortunately, the limitations I was forced to work around to get CustomJS working on mobile devices make the syntax very strict, so your CustomJS classes can't include an import statement.

I'm not sure if it'll work, but you could try importing it inside a `dataviewjs` block. If you're able to somehow import it, then you could just pass it as an argument to any methods you have in your CustomJS classes.

**Comment by tilmanbergt** [comment]
thanks @saml-dev for your explanation. I understand that. I am now already in the process of transitioning my script into a proper obsidian extension. But I am still grateful for the CustomJS extension to provide me with a nice and easy starting ground.

**Comment by saml-dev** [comment]
Happy you got some use out of it!

**Comment by d0020002** [comment]
I am having similar issue!
i want to import https://github.com/markedjs/marked or something like this.
As I can see I can't import from custom-js files. How can i install "marked" and pass through argument from dataview.js?

Basically how can i import packages in dataview or custom-js files?

**Comment by saml-dev** [comment]
You can't import packages in custom-js files. Custom js is still running inside Obsidian, and obviously we don't have access to npm from inside their run time.
