### ISSUE TITLE
Is class inheritance possible ?

### ISSUE THREAD

**Issue by LilaRest** [saml-dev/obsidian-custom-js#40]
Hi, I'm just writing some Dataview helpers for my Obsidian vault and I would like to setup class inheritance to make code cleaner and easier to maintain.

This ones looks like that : 
> elements.js
```js
class Elements {
  type = "";

  /**
   * Return all notes of the element type
   * @returns DataArray
   */
  getAll () {
    return DataviewAPI.pages().where(n => n.type === this.type);
  }
}
```
> tasks.js
```javascript
class Tasks extends customJS.Elements {
  type = "TA";
  
  // Other method specific to tasks only
  // ...
}
```

However this code doesn't work and customJS raises an error at load-time indicating that the `Elements` class is not a constructor : `TypeError: Class extends value #<Elements> is not a constructor or null`

Is there any way to achieve that or am I wrong somewhere ?
Thanks in advance for your help,
Lila :)

**Comment by LilaRest** [comment]
Ok I've solved this quite easily by simply adding `.constructor` after the extended class statement :
> tasks.js
```js
//                                   here
//                                    |
//                                    v 
class Tasks extends customJS.Elements.constructor {
  type = "TA";
  
  // Other method specific to tasks only
  // ...
}
```
Closing the issue for now.

**Comment by LilaRest** [comment]
Re-opening that issue because a bunch of errors are thrown in the console. Note that this is not critical since all works as expected with my above fix and the usage of `forceLoadCustomJS()`.

Here are the errors :
![image](https://user-images.githubusercontent.com/48853371/211393271-7ebb3850-043d-4be9-9fa0-4bbe1a5aebdf.png)

Here is my guess about what happens : 
- During the first initialization of CustomJS (at Obsidian startup), the loading of `tasks.js` fails because in that script I'm trying to use `customJS` object during its own initalization process (leading to the `customJS is not defined` error).
- However the load of `elements.js` succeed because I don't make any direct usage of the `customJS` object in that script
- At that point, any reference to `customJS.Tasks` should fail because the `Tasks` class has not be properly loaded
- But in my case it works because, in my DataviewJS, I'm calling `await forceLoadCustomJS()` before any usage of the `customJS.Tasks` class
- `await forceLoadCustomJS();` performs a second loading of all CustomJS classes, and the loading of `tasks.js` is successful that time because the `customJS` object has already been loaded during the first load of CustomJS

So a way to fix that could be to make the `customJS` object available in scripts during its own initialization.

**Comment by saml-dev** [comment]
I just cut a release with your code. 1.0.13. I accidentally uploaded main.ts at first instead of main.js so let me know if Obsidian is giving any trouble with it and I'll just redo it with 1.0.14 haha

**Comment by LilaRest** [comment]
> I just cut a release with your code. 1.0.13. I accidentally uploaded main.ts at first instead of main.js so let me know if Obsidian is giving any trouble with it and I'll just redo it with 1.0.14 haha

Thanks haha, it seems to work perfectly :)
