### ISSUE TITLE
Awesome Thank you!!! Am I doing it right?  – an idiots showcase ;) – naive approach for link based "command execution"

### ISSUE THREAD

**Issue by tschnibo** [saml-dev/obsidian-custom-js#42]
Hey, some noise... **Thank you for this plugin, I like it a lot!!**
_just overwhelmed by power of this plugin. And now, I d'like to show off and ask if this is "in scope" or just working by chance:_

### Situation:
I am using a Workspace for my daily work. In some foldernote "index file" (just random idea, on random note) I wanted to have a link to "reset" the view back to this Workspace. I could do this via "Buttons" Plugin. But with this plugin I was struggling already in the past.

### Solution:

I have the "Homepage" Plugin installed, and set the "Homepage" to the "Workspace" I like to load when starting my _work_.

No I have this CustomJS Script in one file: _see down below, for less "funny" solution_

```
// in vault at 30-40 organisation/obsidian/customjs/js/OPEN_HOMEPAGE.js
class OpenHomepage {
    doit() {
    window.app.commands.executeCommandById( "workspace:close");
    window.app.plugins.plugins['homepage'].openHomepage();

    return "`$= const {OpenHomepage} = customJS; OpenHomepage.doit()`" ;

    } 
}
```

and a separate `.md`file with the following inline statement:

```
`$= const {OpenHomepage} = customJS; await forceLoadCustomJS(); OpenHomepage.doit()`
```

in another Obsidian `.md` file, I can use this _functionality_ like this:

```
 [[OpenHomepage]]
```

_with an internal link pointing at the `.md`file with the embedded command in it_

(it is helpful to disable automatic preview triggering on "hovering", just so that it doesn't trigger the workspace reload all the time)

### Discussion

First this did not work multiple times. The original page was pasted into the file with the embedded command (very strange 🧐). Now I changed the js to return the original command – this seems very hacky, but working for now :). _is it hacky, or is this rather "how it is done"?_ 😅

I am not a good js dev, so maybe I am missing a very obvious "much easier way" – what do you think?

_and of course, this all is just a silly sidequest, I could just use a keyboard shortcut for the "Homepage" plugin. But, maybe, in case this works on mobile too (I'll need to try first), this link-based approach even has some worth..._

### Thank you

I hope to not have disturbed or annoyed, but rather entertained – and of course I am happy for feedback, even content wise ;)

## edit:

**sorry for the noise!**

I figured out that this file with the inline js doesn't get changed... so the "return value" is not relevant, I guess... The fact that it is working now, and wasn't before. Has maybe rather somehting to do with some other mistakes I made. And with the necessity to do the `forceloadCustomJS()` first.

So at the moment it seems like this "circular extra" is not needed. Good stuff :)

I changed the js file to:
```
// in vault at 30-40 organisation/obsidian/customjs/js/OPEN_HOMEPAGE.js
class OpenHomepage {
    doit() {
    window.app.commands.executeCommandById( "workspace:close");
    window.app.plugins.plugins['homepage'].openHomepage();

    //return "`$= const {OpenHomepage} = customJS; OpenHomepage.doit()`" ;
    return "zero" ;

    } 
}
```

still working 💯 

Cheers!!!

**Comment by saml-dev** [comment]
I say if it works don't change it 😁 you shouldn't need to return anything from your function, you can delete the return statement

**Comment by saml-dev** [comment]
Definitely an interesting use case, cool idea.

**Comment by tschnibo** [comment]
Hey, thank you for your reply!

Yes, I was intrigued by this. It **feels sort of like a magic bullet** because:
- links can turn into buttons, or almost whatever you like. (**links get extremely powerful like this, they can do everything, I feel :)** )
_e.g. one could use the js and access the file with the link on it via the obsidian API (last active file, or something like this, maybe, or then "refering file" or such) to get the current file, modifiy it, analyze it..., and then like this really do everything which the button plugin does, as far as I see from memory :). And many other plugins too, it feels like breaking free from a "cage" ;), almost :)_
**of course I don't know if such files do disturb the general file processing / indexing in some ways. But I guess normally the inline dataviewjs should just be loaded when a note is opened, and not during some background processes**

- because this is mediated by "file", one can even access this via clicking on the file in the file explorer.

_another possible usecase: I felt like building navigational elements into the daily notes, or maybe a TOC in a more extensive note. But this resulted in having lots of dataviewjs on many pages. How about putting the dataviewjs into a separate file, and let your plugin do the job, with the above shown "trick", and just use whatever one wants from it in the original file – by just putting a normal "link" on.  So the original note doesn't get bloated with js code. I mean, **not tested, this is just associative thinking here!!!* how about you want a toc, you put the link to the special toc file. In the background the js reads your current note gets all the headings and then maybe opens a hovernote (<- was it called like this), an overlay with your current notes headers as links. So the toc would stay in place, even when you are moving in your note. Of course the links in this special TOC would need to be "intelligently" made too, in order to use them to navigate the currently opened file... so maybe this is not a extremely simple idea, and much to complicated... but I guess one could come up with lots of ways to **empower** internal obsidian links like this, some e.g. using the preview option__ OMG: I would like to proceed thinkering with this. One could build a complete custom "menue" in form of a collection of superpowered links and pin this collection-note to the righthand panel... 😅😇 But this whole tinkering is not inline with my other goals, so I'll not do it (read down below, in case all this private insight is of any interest to you ;).

**((Maybe this would even work in order to make embeds truly dynamical. Not tried, but maybe one could make a single "daily-note-navigation" file with the above mentioned trick, and on opening a daily note, this daily-note-navigation file is loaded as an embed, and your plugins work would then be to read the current _date_ of the open daily-note-filename and build the navigational links on the fly – just putting one embed into the daily note template instead of a mixture of dataviewjs templater and so on.... I guess one could just use inline dataviewjs directly on the daily note, but, I think an internal link is so much cleaner :) ))**

In case I should further elaborate on how I **guess, fantasize...** that this could be used, just let me know ;) (OMG, I feel like bursting from ideas... ;) ).

Thank you a lot, and have a great time, take care! :)

**Here follows some private insight, why I just switched away from obsidian, sorry, just needed to get this out somewhere I guess :)**
To be completely honest – just one day after working on the here showcased trick, I switched to logseq – because at the end of the day, I did so much tinkering with obsidian and all these plugins, and workarounds for special implementation of pseudo js code (Dataviewjs), templater and so on.... seemingly unnessesarily, because the only thing I really wanted is a place to write down my toughts, to acumulate the findings of everyday web-enquiries, lists like "movies I want to see", "jobs id like to explore", "interests", "interesting communication...", just for everything – but it should be simple, I guess – and despite finding it really interesting to constantly optimize this, I sort of lost the goal out of sight in obsidian, by far even ;)

I guess this "very late" finding thanks to your package just came a bit late.

And I don't mean to critisize the obsidian approach here, of course. It was me, starting to build "navigation" and lots of "features" into the daily note. When transfering them to logseq I sure had to remove lots of dataview (inline, non-inline) code. For me the blank sheet Wiki-Style of obsidian felt really intuitive in the first moment – but despite not having really a clue with logseq, I recognize how much easier it is to have all the interconnection options built in. I'll try to stay of plugins as much as I can :). A year ago the "block-style" turned me off, but now I see how this solves like almost all my "problems" I had with obsidian.

**Comment by saml-dev** [comment]
Ha, it's funny you mention moving off of Obsidian. I had a similar experience. I found I was spending more time configuring my workspace when I really just needed to write things down and move on. So I switched to Notion which is purposely not that configurable so I would just focus on the information itself rather than the app. So I don't use Obsidian anymore either :P 

I'm glad you had some fun messing with CustomJS! Your idea is very clever. I'll rename this issue so others can find it and maybe use it for inspiration.

**Comment by tschnibo** [comment]
Haha 👍 
Thank you, and same to you! 

I was biased, as always: here probably "out-group bias", someone who maintains a plugin, is sure be working with the tool... ;)
Well, it is always nice to have some shared reality, thank you – I feel validated!

Happy with Notion so far?
Just found myself generating a template in logseq, better stop immediately with this action, you, or this "issue" here rather, just reminded me of this :)

I guess obsidian is just for people which are very diciplined :)

have a great time!
