### ISSUE TITLE
Question about your example pulling daily tasks

### ISSUE THREAD

**Issue by clearf** [saml-dev/obsidian-custom-js#44]
In your example of how you use CustomJs to pull daily tasks, I noticed there's a category field ```t.category```. 

I haven't seen reference to category anywhere else in the obsidian task infrastructure. I'm curious what that is. Is that something that's easy to share?

**Comment by saml-dev** [comment]
In that example, each task was a note. The note has `category` in the frontmatter like so
```
text: call mom
category: personal
```
