### ISSUE TITLE
templater issue

### ISSUE THREAD

**Issue by Granaat** [saml-dev/obsidian-custom-js#46]
When inserting a template using templater, an error is created stating that the "x.js" file doens't export a default function.
I tried to convert the classes into function exports, but that results in customJS not working.

Is there any solution for this?

**Comment by saml-dev** [comment]
can you share your templater template?

**Comment by saml-dev** [comment]
really just the customjs import line

**Comment by Granaat** [comment]
I've figured it out & forgot to close the issue.
When the rootfolder of templater scripts & customjs scripts is the same, there's an issue as templater expects function exports & customjs expects classes.

Therefore no functions can be shared unfortunately, but it's resolved with moving them to their own separate subdirectory.
