### ISSUE TITLE
Semicolon at the end of class causes error

### ISSUE THREAD

**Issue by Aeneas-Herodotus** [saml-dev/obsidian-custom-js#47]
I'm not sure if this is expected behaviour but a semicolon at the end  of the class statement results in an error: "Evaluation Error: TypeError: Cannot read properties of undefined"

**Comment by saml-dev** [comment]
are you talking about a semicolon here?
```
class Coolify {

// blah blah

}; // <-- this one
```

**Comment by Aeneas-Herodotus** [comment]
Yeah, that's right. I just began learning to code to be able to use more advanced features of Obsidian and Dataview, so I'm not yet very familier with all the syntax. But I couldn't find anything online about Javascript class statements not being able to have semicolons at the end, so I'm not sure if I'm missing somehting and Its just expected behavior or not.

**Comment by saml-dev** [comment]
Yeah classes don't have semicolons after their declaration. Same as declaring a function.
