### ISSUE TITLE
Basic Javascript Functions Not Defined

### ISSUE THREAD

**Issue by tbarlow12** [saml-dev/obsidian-custom-js#49]
Hello! Thanks for this plugin. Really excited to use it.

I'm running into this problem when trying to execute code in Templater. Basic functions like `console.log` or string `.split()` are trying to be executed and it says 

```
console.log(...) is not a function
```

or 

```
split is not defined
```

Am I missing something I'm supposed to be doing in the setup?

Thanks!

**Comment by saml-dev** [comment]
Please share your templater script and CustomJS script if you have any.
