### ISSUE TITLE
How do I abstract utility functions?

### ISSUE THREAD

**Issue by vi-cat** [saml-dev/obsidian-custom-js#62]
I have a main class file (Projects.js) that runs queries and stuff. I want to abstract away some utility functions (into Utils.js), but I can't figure out how to import those into the main class file.

**Comment by thakichowdhury** [comment]
You could just use the `require` function.

e.g.
// in Utils.js
function addTwoNums(num1, num2) {
  return num1 + num2;
}

exports.addTwoNums = addTwoNums

// in Projects.js
const utils = require("Utils.js")
utils.addTwoNums(1, 2)

**Comment by thakichowdhury** [comment]
Nevermind, I guess require breaks the plugin...

**Comment by thakichowdhury** [comment]
@vi-cat I used dependency injection as a workaround. Please see below for example.

// Test.js
```
class Test {
  constructor() {
  }

  /*** should be hash with keys as the name of dep, and dep as value ***/
  injectDependencies(dependencies) {
    Object.keys(dependencies).forEach(dep => {
      this[dep] = dependencies[dep]
    })
  }

  /*** if you want to use injected dependencies in your method definitions, set a method to return the dependency ***/
  util() {
    return this.util
  }
}
```

// dataviewjs
```
const { Test, Util } = customJS
Test.injectDependencies({ util: Util, dv, moment })
// you can check to see if the class has the property names
dv.span(Object.getOwnPropertyNames(Test))
```

**Comment by thakichowdhury** [comment]
Alternatively, if you would like to not include the `injectDependencies` method into every class definition, you could make the dependency injection a decorator and (kind of) decorate your classes on initial assignment.

// DepInjectDecorator.js
```
class DepInjectDecorator {
  decorate(targetClass) {
    targetClass.injectDependencies = this.injectDependencies
    return targetClass
  }

  /*** should be hash with keys as the name of dep, and dep as value ***/
  injectDependencies(dependencies) {
    Object.keys(dependencies).forEach(dep => {
      this[dep] = dependencies[dep]
    })
  }
}
```

// dataviewjs
```
const {Test, Util, DepInjectDecorator} = customJS
const test = DepInjectDecorator.decorate(Test)

Test.injectDependencies({ util: Util, dv, moment })

// you can check to see if the class has the property names
dv.span(Object.getOwnPropertyNames(Test))
```

**Comment by WimTibackx** [comment]
Hi @vi-cat , @thakichowdhury,
Note that you can also use the `customJS` destructuring (`const {Util} = customJS`) within a customJS script. It's essentially the same as the last comment by @thakichowdhury, but without the need to put it into every dataviewjs snippet. This means your dataviewjs snippets can sometimes be single-liners.

For example, I have a folder registered to customJS containing two files, `crmviews.js` and `viewUtils.js`.

ViewUtils.js has : 

```js
class ViewUtils {
  // ...
  renderButton(container, text, onClick) {
    const btn = container.createEl('button', {text: text});

    let busy = false;
    btn.addEventListener('click', async () => {
      if (busy) {
        return;
      }
      busy = true;
      btn.toggleClass('disabled');

      await onClick();

      btn.toggleClass('disabled');
      busy = false;
    })
  }
}
```

While crmviews.js has:
```js
class CrmViews {
  async renderUpdateMail(dv) {
    const {ViewUtils} = customJS;
    ViewUtils.renderButton(dv.container, 'Parse', async () => {
      console.log('Details not important :)');
    });
  }
}
```

**Comment by thakichowdhury** [comment]
@WimTibackx Ohh, I hadn't even thought of that! Yes, that's a much more elegant solution!

**Comment by saml-dev** [comment]
@WimTibackx 's solution is the most ergonomic IMO. I'm going to close this issue as there's a few different solutions posted. 

As noted by @thakichowdhury , any kind of typical js import will break - that's because we have to `eval` the files in Obsidian, that's the only way to get it to work on mobile apps.

Thanks all for sharing solutions!

**Comment by vi-cat** [comment]
Thanks guys! @WimTibackx 's solution was the winner for me. So much cleaner! Although I wish I would be able to do this:

```
constructor() {
   this.ViewUtils = customJS.ViewUtils;
}
```

It seems at that point it returns null.

**Comment by saml-dev** [comment]
It's possible this is due to file loading order. The files are loaded in alphabetical order by file name (so not including any directory names). Since ViewUtils comes near the end of the list that might be why it's null. Try renaming your ViewUtils file to aViewUtils just to test that theory.

**Comment by AlfonsoRReyes** [comment]
My apologies for reviving this thread. I am having some trouble running CustomJS script in my iPad. The scripts run fine in my desktop. 

I am suspecting that what’s breaking the utility scripts is that I have placed them in separate folders, not under the customJS settings folder. The main customJS script - called from dataviewjs is located under the customJS settings folder.

I did this trying to organize my scripts. Something like folders:
- Extras
   - customJS
   - module-utils 
   - module-common
   - module-settings
   - 
   
To import any of the .js script under any of these sub folders I use a function.

```
class ImportTwoClasses {
    /* -------------------------------------------------------------------------- */
    /*                                Import Section                              */
    /* -------------------------------------------------------------------------- */
    static importModule(moduleFolderSuffix, moduleFile) {
      // Code of function
      const { obsidian, app } = self.customJS || {};
      if (obsidian == null || app == null) throw new Error("customJS is null.");
      let adapter = app.vault.adapter;
      if (adapter instanceof obsidian.FileSystemAdapter) {
        const modulePath =
          adapter.getBasePath() +
          "/Extras/scripts_module_" +
          moduleFolderSuffix +
          "/" +
          moduleFile;
        delete global.require.cache[global.require.resolve(modulePath)];
        return require(modulePath);
      }
      throw new Error("Obsidian adapter is not a FileSystemAdapter.");    
    }
    
  
    Classes = ImportTwoClasses.importModule(
      "demo",
      "person-animal.js"
    ); 
  
  
      /**
       * @param {Object} dv DataView object of Obisidian extension.
       */
      helloClass(dv) {

        const {Animal, Person} = this.Classes;
        const animal = new Animal();
        const person = new Person();

        dv.span(animal.type)
        dv.span("<br>")
        dv.span(person.type)
      }
    }
   ```

This mechanics work in desktop but it won’t in mobile.

any suggestions?

**Comment by saml-dev** [comment]
I would recommend just making a Utility class that contains the functions you want to use. They should take in all the arguments they need and not rely on any persistent or eternal state. Then just make sure the directories that contain your custom JS files are configured in the custom JS settings.

This method avoids needing `import` or `require` which can be finnicky in a runtime environment
