### ISSUE TITLE
Scripts not loading from Folder

### ISSUE THREAD

**Issue by Eforen** [saml-dev/obsidian-custom-js#63]
named folder `.customjs` set it in the settings
put a file in it `.customjs/test.js`

```js
class test {
    test() {
        console.log("test")
        return "Test";
    }
}
```

Open dev console ran `await forceLoadCustomJS()` then tried `test.test()` and `window.test.test()`

None of this worked

**Comment by julesvirallinen** [comment]
see the docs for how to load customJS functions

In dataviewjs codeblock or other obsidian js-environment: 

```
const {test} = customJS

test.test()
```

**Comment by saml-dev** [comment]
Thanks @julesvirallinen . 

@Eforen please try using CustomJS as noted above and reopen if it still doesn't work.
