### ISSUE TITLE
How add custom-js to my obsidian?

### ISSUE THREAD

**Issue by mxcdh** [saml-dev/obsidian-custom-js#65]
I added the folder with custom.js, but the plugin did not detect it. 
https://share.cleanshot.com/CcYFj7q1
You can find the file structure of a .js file by referring to its format.

How should I correctly add the .js file?

**Comment by svenschuldt** [comment]
Hi, I have a similar problem:
- I have defined the folder within the settings of the plugin (9 setup/Javascript) but none of the scripts are being loaded
- when I execute customJS from the console they are also not visible
- only when I add them individually in the "individual Files" option of the settings they are loaded and work

**Comment by mxcdh** [comment]
@mnaoumov 
1. It is not detectable.
2. Can you explain? This is my example script. What should I rewrite? https://dsh.re/824459
@svenschuldt 
Which OS are you using?
In my case, that is not working.

**Comment by svenschuldt** [comment]
@mxcdh , I am using macOS Ventura 13.5.2 (22G91)

**Comment by saml-dev** [comment]
@mxcdh have you tried removing the `./` from the start of your path?

**Comment by mnaoumov** [comment]
@mxcdh current plugin has a few use-cases

1. `customJS` global variable, which you can use in `Developer Tools Console`, `dataviewjs`, `Templater` scripts etc. To check if it works you should open `Developer Tools Console` (via `Command + Shift + I`) and type `customJS.dvTasks`. If it doesn't show an error, then your config is working properly.

2. [Invocable scripts](https://github.com/saml-dev/obsidian-custom-js#invocable-scripts). `dvTasks.js` is not an invocable script, that's why you don't see it in the list on step 4 on your screenshot

**Comment by YousufSSyed** [comment]
I'm having this issue too

**Comment by mnaoumov** [comment]
@YousufSSyed what happens if you go to the developer console and type `window.forceLoadCustomJS()`?

**Comment by YousufSSyed** [comment]
I have a file `script.js` inside the `Scripts` folder and this is the result:
<img width="1061" alt="Screenshot 2023-10-22 at 11 39 27 AM" src="https://github.com/saml-dev/obsidian-custom-js/assets/42646062/b983c360-355a-4e67-9045-09ec8d3f7a12">

<img width="1192" alt="Screenshot 2023-10-22 at 11 39 44 AM" src="https://github.com/saml-dev/obsidian-custom-js/assets/42646062/9c24efdf-6778-4f24-b96c-a5afef1cce8b">

**Comment by mnaoumov** [comment]
@YousufSSyed that's because of your **Individual files** setting

**Comment by YousufSSyed** [comment]
I changed the file to `Scripts/script.js` and this is the script:

```
class Script {
    getQuoteOfTheday() {
        let file = this.app.workspace.getActiveFile();
        let currentTime = moment().format('YYYY-MM-DD HH-h:mm:ssA');
        let quote = await fetch("https://api.quotable.io/random").then(response => response.json());
        app.vault.append(file, `\n- **${currentTime}, ${quote["author"]}:** ${quote["content"]}`)
    }
}
```
<img width="1194" alt="Screenshot 2023-10-22 at 12 14 46 PM" src="https://github.com/saml-dev/obsidian-custom-js/assets/42646062/c78dbaa5-70f4-4ea6-bc82-4e1e7f392d75">

**Comment by mnaoumov** [comment]
@YousufSSyed 

1. Remove the **Individual files** completely
2. Add word `async` before the name of your function

**Comment by YousufSSyed** [comment]
Like this?

```js
class Script {
    aync getQuoteOfTheday() {
        let file = this.app.workspace.getActiveFile();
        let currentTime = moment().format('YYYY-MM-DD HH-h:mm:ssA');
        let quote = await fetch("https://api.quotable.io/random").then(response => response.json());
        app.vault.append(file, `\n- **${currentTime}, ${quote["author"]}:** ${quote["content"]}`)
    }
}
```

**Comment by mnaoumov** [comment]
@YousufSSyed yes, but you made a typo

**Comment by YousufSSyed** [comment]
Oh I made that typo while pasting it in the comment. I wrote `async` in the script and it still doesn't show up when trying to add an invocable script.

**Comment by mnaoumov** [comment]
@YousufSSyed you didn't make it invocable

https://github.com/saml-dev/obsidian-custom-js#invocable-scripts

**Comment by YousufSSyed** [comment]
My Individual scripts is blank and I wrote `Scripts` for the folder. When I press "Register invocable script" nothing shows up.

**Comment by mnaoumov** [comment]
@YousufSSyed you didn't read properly what invocable script is

**Comment by YousufSSyed** [comment]
I'll admit, I didn't realize "Invocable Script is the class with the defined method" meant `async invoke()` specifically, and I thought you would've pointed that out if I asked if it looked right.

But now that i registered the script I'm wondering what this plugin can or can't do, because now I have this error TypeError: Cannot read properties of undefined (reading 'workspace'), when running `let file = this.app.workspace.getActiveFile();`. The code works fine when I paste it into the console.

**Comment by thelegend09** [comment]
@YousufSSyed Here are all the steps in order: 

1. In the CustomJS settings, you can set individual files as a script, or you can set a folder that contains several JS files. It is seperate—you don't need both for the same file. (Note: If you use an individual file, make sure to add the path as well.)
2. Then, open your script file and make it fit this template:

```javascript
class getFonts {  // you can change the name of the class
  async invoke() {  // you cannot change the name of this 
    console.log("Hello World")  // you write your code here, inside "invoke"
  }
}
```

3. Go back to CustomJS settings, and add click on the button "Register invocable script". You should see your script there.
4. (optional) To make your script run at startup, click on the button "Add startup script", and you should see your script there.

I think the documentation could be clearer.

**Comment by mnaoumov** [comment]
@thelegend09 if you have suggestion how to make the suffering documentation clearer, please make a PR

**Comment by summerowls0521** [comment]
> @thelegend09 if you have suggestion how to make the documentation clearer, please make a PR

I have a suggestion, state that invokable (and if others, for them too) classes must be the only thing defined in the file. It wasn't working for me because I declared a constant outside of the class. If I hadn't come here and found out about `window.forceLoadCustomJS()` I'd still be stuck.

**Comment by saml-dev** [comment]
@summerowls0521 thanks, updated https://github.com/saml-dev/obsidian-custom-js/commit/8c1b7b9a63f3ea4c93ad139c0106ebcfbcb25b2d
