### ISSUE TITLE
Update/reinstall of plugin results in: Error: Request failed, status 404 

### ISSUE THREAD

**Issue by DrewCam** [saml-dev/obsidian-custom-js#68]
Tried updating today via community hub, but resulted in a 404 error, so thought to try reinstall the plugin. Which gets the same error. Also tried from a different device with the same error. 

Wondering if its the same result for anyone else?

![image](https://github.com/saml-dev/obsidian-custom-js/assets/5970574/ba64807e-a9a7-4f93-8e08-69d54842722a)

Console 

![image](https://github.com/saml-dev/obsidian-custom-js/assets/5970574/9c404c22-fff6-4295-9f2b-7bce4d80c13a)

```
app.js:1 Error: Request failed, status 404
    at new t (app.js:1:1826037)
    at Hj (app.js:1:1826229)
    at app.js:1:1826906
    at app.js:1:237027
    at Object.next (app.js:1:237132)
    at a (app.js:1:235850)
```

**Comment by chrisgrieser** [comment]
I also have that issue

**Comment by sascharo** [comment]
Same problem; I can't install the latest version.

**Comment by xt0rted** [comment]
Looks like the latest release used `1.0.15` as the version number, but the GitHub release used [`1.0.16`](https://github.com/saml-dev/obsidian-custom-js/releases/tag/1.0.16) so the manifest file can't be downloaded. There is a [`1.0.15`](https://github.com/saml-dev/obsidian-custom-js/releases/tag/1.0.15) tag, but there's no release associated with it.

Url causing the error: https://github.com/saml-dev/obsidian-custom-js/releases/download/1.0.15/manifest.json

**Comment by saml-dev** [comment]
Sorry all, this was my bad. That's what I get for never making a script to cut the release :P Just updated everything to 1.0.17, please reopen this if it you're still having issues after upgrading
