### ISSUE TITLE
Feature request: Allow writing in JS scripts right in the plugin settings

### ISSUE THREAD

**Issue by Oneechan69** [saml-dev/obsidian-custom-js#73]
I'd like to have able to have a bunch of small JS scripts in one place: the plugin settings. Each script would have a name and a large text box next to it to paste the code in, and can be added as invocable scripts.

**Comment by saml-dev** [comment]
Hey, thanks for sharing your thoughts. I think this would bloat the plugin code too much without providing that much value, so I'm going to close the issue.
