### ISSUE TITLE
Evaluation Error on mobile

### ISSUE THREAD

**Issue by joshmedeski** [saml-dev/obsidian-custom-js#83]
Hey @saml-dev, thanks for this plugin. I'm excited to get my custom dataviews working on mobile! 🔥

Here is the class:

```js
class Area {
  async area(args) {
    const { dv } = args;
    const area = dv.current();

    dv.header(1, "Relationships 👥");
    dv.list(
      dv
        .pages('"Relationships 👥"')
        .filter((relationship) => {
          return relationship.area && relationship.area.path === area.file.path;
        })
        .map((project) => project.file.link),
    );

    // ... more sections just like this ...
  }
}

```

Then I call this on the document:

```js
const {Area} = customJS
await Area.area({dv})
```

It works on desktop! But I get the following error on mobile:

![IMG_1031](https://github.com/saml-dev/obsidian-custom-js/assets/2036594/1fe5ac4b-e348-4ada-b094-87258b31557d)

Unsure how to debug it, I would appreciate some help 😁

**Comment by julesvirallinen** [comment]
Hmm, does your function need to be async / awaited?

**Comment by joshmedeski** [comment]
I dropped the async await and got the same error. It's just `dv.header` `dv.list` function calls.

**Comment by saml-dev** [comment]
Are you sure it's the exact same error? The stack trace you posted above mentions `asyncEvalInContext@` which also made me think async might be the problem.

**Comment by joshmedeski** [comment]
![IMG_1033](https://github.com/saml-dev/obsidian-custom-js/assets/2036594/3268f331-8a4e-4c30-83a7-4583e34cde6f)

It's only slightly different, same error.

**Comment by saml-dev** [comment]
Sorry I don't use obsidian anymore so I can't offer much direct help. However if I was debugging this I would make the function some kind of one-liner like `return "hey"`. Then see if it works. If it does, then there's something in your code causing the bug. If it doesn't, then it's either CustomJS or more likely something else about your set up that isn't quite right.

**Comment by joshmedeski** [comment]
I never figured this out. If I decide to revisit it I can reopen this ticket, thanks for offering support.
