### ISSUE TITLE
Newbie: help to code a function

### ISSUE THREAD

**Issue by louwelyn-jeremy** [saml-dev/obsidian-custom-js#87]
Hi,
I want to do a thing in my vault and your plugin seems to do what i want.

But i'm not a JS coder, so i need your help (if it's possible)

I try to have a subfolder in "C:/projects/" for each project.  The name of the subfolder and the name of my note in obsidian are the same.

I try to create a function that:

1. check if a folder with the name of the note exist in "C:/projects/" 
2. if it's true --> show "👍"
3. if it's false --> show "❌"

thank you  for your time 🙏

**Comment by mnaoumov** [comment]
@louwelyn-jeremy this is not the appropriate place for such questions. Your question has nothing to with the plugin. All you need is some JavaScript help, which you should look for elsewhere
