### ISSUE TITLE
feature request: support codeblocks for syntax highlighting

### ISSUE THREAD

**Issue by vitaly** [saml-dev/obsidian-custom-js#9]
right now I can either use `.js` files, which can't be edited directly in obsidian, or use `.md` files with js code in them, which do not have proper syntax highlighting.

it would be nice if it was possible to use `.md` files with frontmatter, and have the actual code inside a `js` codeblocks:
~~~markdown
---
created: 2001-01-01
tags: snippet, dataview
type: customjs
---
```javascript
class Foo {
   ...
}
```

```javascript
class Bar {
   ...
}
```
~~~

this format should be easy to detect by checking for frontmatter.

**Comment by NomarCub** [comment]
There's a plugin that lets you view js files within Obsidian: https://github.com/dbarenholz/obsidian-plaintext
It has syntax highlighting in the works too: https://github.com/dbarenholz/obsidian-plaintext/issues/10

**Comment by danielo515** [comment]
There is also a plugin that adds syntax highlights to code blocks. Won't that fix your problem?

**Comment by saml-dev** [comment]
This issue was opened almost 2 years ago. Sounds like there are workarounds now with other plugins, which makes more sense than building this into customjs.

**Comment by NomarCub** [comment]
There's no workaround that I know of, the one I linked is still open. If you know any, please share it, @saml-dev.

**Comment by danielo515** [comment]
> There's no workaround that I know of, the one I linked is still open. If you know any, please share it, @saml-dev.

https://github.com/deathau/cm-editor-syntax-highlight-obsidian

**Comment by NomarCub** [comment]
That plugin hasn't been updated for over 2.5 years and judging by its GitHub issues, not really functional.

**Comment by danielo515** [comment]
> That plugin hasn't been updated for over 2.5 years and judging by its GitHub issues, not really functional.

Not all plugins need to be updated on a weekly basis. I am using that plugin, and it is perfectly functional in bot edit and preview modes:

<img width="559" alt="image" src="https://github.com/saml-dev/obsidian-custom-js/assets/2270425/0b7a1df1-7dd1-4fc5-b3e4-0450097f38b6">
<img width="559" alt="image" src="https://github.com/saml-dev/obsidian-custom-js/assets/2270425/841acc94-a940-4ecd-9a26-49fe73d5c50b">

What else do you want?
