### ISSUE TITLE
Unable to Use Two Example Cases from Readme, Both Throw Errors

### ISSUE THREAD

**Issue by Brinmon** [saml-dev/obsidian-custom-js#93]
**Issue Description:**

Hello, I’m trying to use the `CustomJS` plugin, but I'm encountering errors when using the examples provided in the `readme`. I’d appreciate any guidance on what might be going wrong.

**Environment:**
- OS: Windows 10
- Obsidian version: v1.5.11
- Plugin versions:
  - CustomJS: v1.0.21
  - Dataview: v0.5.67

---

**Error 1:**

I added a `console.log` to test whether the JavaScript code was loading correctly, and I successfully got the output `"Test plugin loaded............"`, but another error followed.

**Screenshot:**
![image](https://github.com/user-attachments/assets/9b473122-4dc5-4a54-a94a-264ca70f0cbb)

**Code (from `createFolderNote.js`):**
```js
class AddCustomMenuEntry {
  constructor() {
    // Binding the event handler to the class context
    this.eventHandler = this.eventHandler.bind(this);
    console.log("Test plugin loaded............");
  }

  async invoke() {
    this.app.workspace.on('file-menu', this.eventHandler);
  }

  deconstructor() {
    this.app.workspace.off('file-menu', this.eventHandler);
  }

  eventHandler(menu, file) {
    // Check the API documentation for this feature
    // https://docs.obsidian.md/Plugins/User+interface/Context+menus
    menu.addSeparator();
    menu.addItem((item) => {
      item
        .setTitle('Custom menu entry text..')
        .setIcon('file-plus-2') // Check the API documentation for available icons
        .onClick(() => {
          // Insert the code to execute when the context menu item is clicked.
        });
    });
  }
}
```

---

**Error 2:**

I encountered a `luxon is not defined` error when running the following code.

**Code:**
```dataviewjs
const {DvTasks} = await cJS();
DvTasks.getOverdueTasks({app, dv, luxon, that: this, date: '2021-08-25'});
```

**Error message:**
```
Evaluation Error: ReferenceError: luxon is not defined
    at eval (eval at <anonymous> (plugin:dataview), <anonymous>:2:35)
```

**Screenshot:**
![image](https://github.com/user-attachments/assets/7ffb44ee-bb98-435b-917f-da552e0453ed)

Any help would be greatly appreciated!

**Comment by saml-dev** [comment]
For the first error, it says `Cannot read properties of undefined (reading 'workspace'`. That means you are calling `.workspace` on something that is undefined. Your code has `this.app.workspace`, so this.app is undefined. You are not setting `this.app` in your constructor so that is why.

For the second error, the DvTasks example is not intended to be copied and pasted as-is, it's just an example of what you can do with CustomJS. I am going to remove it from the README so others don't get confused.
